#
# dummy WireGuard configuration file
#
[Interface]
PrivateKey = <PRIVATEKEY>
Address = 203.0.113.1/32, 2001:db8::1/128
DNS = 203.0.113.254

[Peer]
PublicKey = cY6jG7Hx837LGsk75MHflpXcdaZw7biyMlpnyMFc9wA=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = vpn.example.com:51820
